import { http, HttpResponse } from "msw";

/**
 * /_/realtime/tdl_attraction.json?1730535529216
 */
export const mockTdlResp = [
  {
    FacilityID: "173",
    FacilityName: "アリスのティーパーティー",
    FacilityKanaName: "ｱﾘｽのﾃｨｰﾊﾟｰﾃｨｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:54",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "172",
    FacilityName: "イッツ・ア・スモールワールド",
    FacilityKanaName: "ｲｯﾂ･ｱ･ｽﾓｰﾙﾜｰﾙﾄﾞ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: "003",
    FacilityStatus: "運営・公演中止",
    StandbyTime: "0",
    OperatingHoursFromDate: null,
    OperatingHoursFrom: null,
    OperatingHoursToDate: null,
    OperatingHoursTo: null,
    OperatingStatusCD: null,
    OperatingStatus: null,
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: null,
  },
  {
    FacilityID: "157",
    FacilityName: "ウエスタンランド・シューティングギャラリー",
    FacilityKanaName: "ｳｴｽﾀﾝﾗﾝﾄﾞ･ｼｭｰﾃｨﾝｸﾞｷﾞｬﾗﾘｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "10",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:47",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "154",
    FacilityName: "ウエスタンリバー鉄道",
    FacilityKanaName: "ｳｴｽﾀﾝﾘﾊﾞｰ鉄道",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "15",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:30",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "19:30",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:11",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:30",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "19:30",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "151",
    FacilityName: "オムニバス",
    FacilityKanaName: "ｵﾑﾆﾊﾞｽ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: null,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "10:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "14:15",
    OperatingStatusCD: "002",
    OperatingStatus: "案内終了",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "14:16",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "10:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "14:15",
        SunsetFlg: false,
        OperatingStatusCD: "002",
        OperatingStatus: "案内終了",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "152",
    FacilityName: "カリブの海賊",
    FacilityKanaName: "ｶﾘﾌﾞの海賊",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "10",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:52",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "158",
    FacilityName: "カントリーベア・シアター",
    FacilityKanaName: "ｶﾝﾄﾘｰﾍﾞｱ･ｼｱﾀｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "15",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "10:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "20:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:47",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "10:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "20:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "179",
    FacilityName: "ガジェットのゴーコースター",
    FacilityKanaName: "ｶﾞｼﾞｪｯﾄのｺﾞｰｺｰｽﾀｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:57",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "170",
    FacilityName: "キャッスルカルーセル",
    FacilityKanaName: "ｷｬｯｽﾙｶﾙｰｾﾙ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "10",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:10",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "181",
    FacilityName: "グーフィーのペイント＆プレイハウス",
    FacilityKanaName: "ｸﾞｰﾌｨｰのﾍﾟｲﾝﾄ&ﾌﾟﾚｲﾊｳｽ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:51",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "166",
    FacilityName: "シンデレラのフェアリーテイル・ホール",
    FacilityKanaName: "ｼﾝﾃﾞﾚﾗのﾌｪｱﾘｰﾃｲﾙ･ﾎｰﾙ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: null,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "10:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "15:00",
    OperatingStatusCD: "002",
    OperatingStatus: "案内終了",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "15:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "10:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "15:00",
        SunsetFlg: false,
        OperatingStatusCD: "002",
        OperatingStatus: "案内終了",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "153",
    FacilityName: "ジャングルクルーズ：ワイルドライフ・エクスペディション",
    FacilityKanaName: "ｼﾞｬﾝｸﾞﾙｸﾙｰｽﾞ:ﾜｲﾙﾄﾞﾗｲﾌ･ｴｸｽﾍﾟﾃﾞｨｼｮﾝ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:48",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "155",
    FacilityName: "スイスファミリー・ツリーハウス",
    FacilityKanaName: "ｽｲｽﾌｧﾐﾘｰ･ﾂﾘｰﾊｳｽ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: "003",
    FacilityStatus: "運営・公演中止",
    StandbyTime: "0",
    OperatingHoursFromDate: null,
    OperatingHoursFrom: null,
    OperatingHoursToDate: null,
    OperatingHoursTo: null,
    OperatingStatusCD: null,
    OperatingStatus: null,
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: null,
  },
  {
    FacilityID: "183",
    FacilityName: "スター・ツアーズ：ザ・アドベンチャーズ・コンティニュー",
    FacilityKanaName: "ｽﾀｰ･ﾂｱｰｽﾞ:ｻﾞ･ｱﾄﾞﾍﾞﾝﾁｬｰｽﾞ･ｺﾝﾃｨﾆｭｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: "2",
    PPStatus: "40周年記念プライオリティパス発行なし",
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "40周年記念プライオリティパス発行なし",
    FsStatusCD: "5",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:11",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "195",
    FacilityName: "スティッチ・エンカウンター",
    FacilityKanaName: "ｽﾃｨｯﾁ･ｴﾝｶｳﾝﾀｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "15",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "10:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "19:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "10:06",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "10:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "19:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "162",
    FacilityName: "スプラッシュ・マウンテン",
    FacilityKanaName: "ｽﾌﾟﾗｯｼｭ･ﾏｳﾝﾃﾝ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "10",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: "1",
    DPAStatus: "販売中",
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:51",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "178",
    FacilityName: "チップとデールのツリーハウス",
    FacilityKanaName: "ﾁｯﾌﾟとﾃﾞｰﾙのﾂﾘｰﾊｳｽ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "194",
    FacilityName: "トゥーンパーク",
    FacilityKanaName: "ﾄｩｰﾝﾊﾟｰｸ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: false,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "161",
    FacilityName: "トムソーヤ島いかだ",
    FacilityKanaName: "ﾄﾑｿｰﾔ島いかだ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: null,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "10:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "15:45",
    OperatingStatusCD: "002",
    OperatingStatus: "案内終了",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "15:46",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "10:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "15:45",
        SunsetFlg: false,
        OperatingStatusCD: "002",
        OperatingStatus: "案内終了",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "180",
    FacilityName: "ドナルドのボート",
    FacilityKanaName: "ﾄﾞﾅﾙﾄﾞのﾎﾞｰﾄ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "160",
    FacilityName: "ビッグサンダー・マウンテン",
    FacilityKanaName: "ﾋﾞｯｸﾞｻﾝﾀﾞｰ･ﾏｳﾝﾃﾝ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "25",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: "2",
    PPStatus: "40周年記念プライオリティパス発行なし",
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "40周年記念プライオリティパス発行なし",
    FsStatusCD: "5",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:02",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "163",
    FacilityName: "ビーバーブラザーズのカヌー探険",
    FacilityKanaName: "ﾋﾞｰﾊﾞｰﾌﾞﾗｻﾞｰｽﾞのｶﾇｰ探険",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: null,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "10:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "16:00",
    OperatingStatusCD: "002",
    OperatingStatus: "案内終了",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "15:47",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "10:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "16:00",
        SunsetFlg: false,
        OperatingStatusCD: "002",
        OperatingStatus: "案内終了",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "168",
    FacilityName: "ピノキオの冒険旅行",
    FacilityKanaName: "ﾋﾟﾉｷｵの冒険旅行",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "10",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:49",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "164",
    FacilityName: "ピーターパン空の旅",
    FacilityKanaName: "ﾋﾟｰﾀｰﾊﾟﾝ空の旅",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "35",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:49",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "174",
    FacilityName: "プーさんのハニーハント",
    FacilityKanaName: "ﾌﾟｰさんのﾊﾆｰﾊﾝﾄ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "30",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: "2",
    PPStatus: "40周年記念プライオリティパス発行なし",
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "40周年記念プライオリティパス発行なし",
    FsStatusCD: "5",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "196",
    FacilityName: "ベイマックスのハッピーライド",
    FacilityKanaName: "ﾍﾞｲﾏｯｸｽのﾊｯﾋﾟｰﾗｲﾄﾞ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "70",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: "1",
    DPAStatus: "販売中",
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:04",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "191",
    FacilityName: "ペニーアーケード",
    FacilityKanaName: "ﾍﾟﾆｰｱｰｹｰﾄﾞ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: false,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "171",
    FacilityName: "ホーンテッドマンション“ホリデーナイトメアー”",
    FacilityKanaName: "ﾎｰﾝﾃｯﾄﾞﾏﾝｼｮﾝ“ﾎﾘﾃﾞｰﾅｲﾄﾒｱｰ”",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "55",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: "2",
    PPStatus: "40周年記念プライオリティパス発行なし",
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "40周年記念プライオリティパス発行なし",
    FsStatusCD: "5",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:54",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "167",
    FacilityName: "ミッキーのフィルハーマジック",
    FacilityKanaName: "ﾐｯｷｰのﾌｨﾙﾊｰﾏｼﾞｯｸ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "10",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:59",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "176",
    FacilityName: "ミニーの家",
    FacilityKanaName: "ﾐﾆｰの家",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "189",
    FacilityName: "モンスターズ・インク“ライド＆ゴーシーク！”",
    FacilityKanaName: "ﾓﾝｽﾀｰｽﾞ･ｲﾝｸ“ﾗｲﾄﾞ&ｺﾞｰｼｰｸ!”",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "70",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: "2",
    PPStatus: "40周年記念プライオリティパス発行なし",
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "40周年記念プライオリティパス発行なし",
    FsStatusCD: "5",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:48",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "175",
    FacilityName: "ロジャーラビットのカートゥーンスピン",
    FacilityKanaName: "ﾛｼﾞｬｰﾗﾋﾞｯﾄのｶｰﾄｩｰﾝｽﾋﾟﾝ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "35",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:18",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "165",
    FacilityName: "白雪姫と七人のこびと",
    FacilityKanaName: "白雪姫と七人のこびと",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "15",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:11",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "169",
    FacilityName: "空飛ぶダンボ",
    FacilityKanaName: "空飛ぶﾀﾞﾝﾎﾞ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:47",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "197",
    FacilityName: "美女と野獣“魔法のものがたり”",
    FacilityKanaName: "美女と野獣“魔法のものがたり”",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "80",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: "1",
    DPAStatus: "販売中",
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:14",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "159",
    FacilityName: "蒸気船マークトウェイン号",
    FacilityKanaName: "蒸気船ﾏｰｸﾄｳｪｲﾝ号",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "10",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "10:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "19:45",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "11:42",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "10:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "19:45",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "156",
    FacilityName:
      "魅惑のチキルーム：スティッチ・プレゼンツ“アロハ・エ・コモ・マイ！”",
    FacilityKanaName: "魅惑のﾁｷﾙｰﾑ:ｽﾃｨｯﾁ･ﾌﾟﾚｾﾞﾝﾂ“ｱﾛﾊ･ｴ･ｺﾓ･ﾏｲ!”",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "10",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "10:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "20:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:47",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "10:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "20:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
];

export const mockTdlRespHandler = http.get(
  "https://www.tokyodisneyresort.jp/_/realtime/tdl_attraction.json",
  () => HttpResponse.json(mockTdlResp),
);

/**
 * /_/realtime/tds_attraction.json?1730535529216
 */
export const mockTdsResp = [
  {
    FacilityID: "234",
    FacilityName: "アクアトピア",
    FacilityKanaName: "ｱｸｱﾄﾋﾟｱ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:25",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "255",
    FacilityName: "アナとエルサのフローズンジャーニー",
    FacilityKanaName: "ｱﾅとｴﾙｻのﾌﾛｰｽﾞﾝｼﾞｬｰﾆｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "70",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "248",
    OperatingStatus:
      "【エリア入場制限中】スタンバイパスまたはプライオリティ・アクセス・エントランスをご利用の方のみ案内中",
    SunsetFlg: false,
    DPAStatusCD: "2",
    DPAStatus: "販売していません",
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "発行していません",
    FsStatusCD: "3",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:08",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "248",
        OperatingStatus:
          "【エリア入場制限中】スタンバイパスまたはプライオリティ・アクセス・エントランスをご利用の方のみ案内中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "202",
    FacilityName: "アリエルのプレイグラウンド",
    FacilityKanaName: "ｱﾘｴﾙのﾌﾟﾚｲｸﾞﾗｳﾝﾄﾞ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: false,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "222",
    FacilityName:
      "インディ・ジョーンズ・アドベンチャー：クリスタルスカルの魔宮",
    FacilityKanaName: "ｲﾝﾃﾞｨ･ｼﾞｮｰﾝｽﾞ･ｱﾄﾞﾍﾞﾝﾁｬｰ:ｸﾘｽﾀﾙｽｶﾙの魔宮",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "115",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: "2",
    PPStatus: "40周年記念プライオリティパス発行なし",
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "40周年記念プライオリティパス発行なし",
    FsStatusCD: "5",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:45",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "236",
    FacilityName: "キャラバンカルーセル",
    FacilityKanaName: "ｷｬﾗﾊﾞﾝｶﾙｰｾﾙ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "10",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "10:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:40",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "10:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "235",
    FacilityName: "シンドバッド・ストーリーブック・ヴォヤッジ",
    FacilityKanaName: "ｼﾝﾄﾞﾊﾞｯﾄﾞ･ｽﾄｰﾘｰﾌﾞｯｸ･ｳﾞｫﾔｯｼﾞ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "10",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "220",
    FacilityName: "ジャスミンのフライングカーペット",
    FacilityKanaName: "ｼﾞｬｽﾐﾝのﾌﾗｲﾝｸﾞｶｰﾍﾟｯﾄ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:30",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:17",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:30",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "239",
    FacilityName: "ジャンピン・ジェリーフィッシュ",
    FacilityKanaName: "ｼﾞｬﾝﾋﾟﾝ･ｼﾞｪﾘｰﾌｨｯｼｭ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "25",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:30",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:09",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:30",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "238",
    FacilityName: "スカットルのスクーター",
    FacilityKanaName: "ｽｶｯﾄﾙのｽｸｰﾀｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:15",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "223",
    FacilityName: "センター・オブ・ジ・アース",
    FacilityKanaName: "ｾﾝﾀｰ･ｵﾌﾞ･ｼﾞ･ｱｰｽ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: "003",
    FacilityStatus: "運営・公演中止",
    StandbyTime: "0",
    OperatingHoursFromDate: null,
    OperatingHoursFrom: null,
    OperatingHoursToDate: null,
    OperatingHoursTo: null,
    OperatingStatusCD: null,
    OperatingStatus: null,
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "6:00",
    operatingHours: null,
  },
  {
    FacilityID: "219",
    FacilityName: "ソアリン：ファンタスティック・フライト",
    FacilityKanaName: "ｿｱﾘﾝ:ﾌｧﾝﾀｽﾃｨｯｸ･ﾌﾗｲﾄ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "140",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: "2",
    DPAStatus: "販売していません",
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:10",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "243",
    FacilityName: "タワー・オブ・テラー",
    FacilityKanaName: "ﾀﾜｰ･ｵﾌﾞ･ﾃﾗｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "65",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: "1",
    DPAStatus: "販売中",
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:17",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "246",
    FacilityName: "タートル・トーク",
    FacilityKanaName: "ﾀｰﾄﾙ･ﾄｰｸ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "50",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: "2",
    PPStatus: "40周年記念プライオリティパス発行なし",
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "40周年記念プライオリティパス発行なし",
    FsStatusCD: "5",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:03",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "232",
    FacilityName:
      "ディズニーシー・エレクトリックレールウェイ（アメリカンウォーターフロント）",
    FacilityKanaName: "ﾃﾞｨｽﾞﾆｰｼｰ･ｴﾚｸﾄﾘｯｸﾚｰﾙｳｪｲ(ｱﾒﾘｶﾝｳｫｰﾀｰﾌﾛﾝﾄ)",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: "003",
    FacilityStatus: "運営・公演中止",
    StandbyTime: "0",
    OperatingHoursFromDate: null,
    OperatingHoursFrom: null,
    OperatingHoursToDate: null,
    OperatingHoursTo: null,
    OperatingStatusCD: null,
    OperatingStatus: null,
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: null,
  },
  {
    FacilityID: "231",
    FacilityName:
      "ディズニーシー・エレクトリックレールウェイ（ポートディスカバリー）",
    FacilityKanaName: "ﾃﾞｨｽﾞﾆｰｼｰ･ｴﾚｸﾄﾘｯｸﾚｰﾙｳｪｲ(ﾎﾟｰﾄﾃﾞｨｽｶﾊﾞﾘｰ)",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: "003",
    FacilityStatus: "運営・公演中止",
    StandbyTime: "0",
    OperatingHoursFromDate: null,
    OperatingHoursFrom: null,
    OperatingHoursToDate: null,
    OperatingHoursTo: null,
    OperatingStatusCD: null,
    OperatingStatus: null,
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: null,
  },
  {
    FacilityID: "228",
    FacilityName:
      "ディズニーシー・トランジットスチーマーライン（アメリカンウォーターフロント）",
    FacilityKanaName: "ﾃﾞｨｽﾞﾆｰｼｰ･ﾄﾗﾝｼﾞｯﾄｽﾁｰﾏｰﾗｲﾝ(ｱﾒﾘｶﾝｳｫｰﾀｰﾌﾛﾝﾄ)",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: null,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "11:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "19:45",
    OperatingStatusCD: "004",
    OperatingStatus: "一時運営中止",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "17:14",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "11:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "19:45",
        SunsetFlg: false,
        OperatingStatusCD: "004",
        OperatingStatus: "一時運営中止",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "227",
    FacilityName:
      "ディズニーシー・トランジットスチーマーライン（メディテレーニアンハーバー）",
    FacilityKanaName: "ﾃﾞｨｽﾞﾆｰｼｰ･ﾄﾗﾝｼﾞｯﾄｽﾁｰﾏｰﾗｲﾝ(ﾒﾃﾞｨﾃﾚｰﾆｱﾝﾊｰﾊﾞｰ)",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: null,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "20:45",
    OperatingStatusCD: "004",
    OperatingStatus: "一時運営中止",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "17:15",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "20:45",
        SunsetFlg: false,
        OperatingStatusCD: "004",
        OperatingStatus: "一時運営中止",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "229",
    FacilityName:
      "ディズニーシー・トランジットスチーマーライン（ロストリバーデルタ）",
    FacilityKanaName: "ﾃﾞｨｽﾞﾆｰｼｰ･ﾄﾗﾝｼﾞｯﾄｽﾁｰﾏｰﾗｲﾝ(ﾛｽﾄﾘﾊﾞｰﾃﾞﾙﾀ)",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: null,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "004",
    OperatingStatus: "一時運営中止",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "17:12",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "004",
        OperatingStatus: "一時運営中止",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "218",
    FacilityName: "トイ・ストーリー・マニア！",
    FacilityKanaName: "ﾄｲ･ｽﾄｰﾘｰ･ﾏﾆｱ!",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "125",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: "2",
    DPAStatus: "販売していません",
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:13",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "247",
    FacilityName: "ニモ＆フレンズ・シーライダー",
    FacilityKanaName: "ﾆﾓ&ﾌﾚﾝｽﾞ･ｼｰﾗｲﾀﾞｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "40",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: "2",
    PPStatus: "40周年記念プライオリティパス発行なし",
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "40周年記念プライオリティパス発行なし",
    FsStatusCD: "5",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:15",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "233",
    FacilityName: "ビッグシティ・ヴィークル",
    FacilityKanaName: "ﾋﾞｯｸﾞｼﾃｨ･ｳﾞｨｰｸﾙ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: null,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "11:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "17:00",
    OperatingStatusCD: "002",
    OperatingStatus: "案内終了",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "17:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "11:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "17:00",
        SunsetFlg: false,
        OperatingStatusCD: "002",
        OperatingStatus: "案内終了",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "257",
    FacilityName: "ピーターパンのネバーランドアドベンチャー",
    FacilityKanaName: "ﾋﾟｰﾀｰﾊﾟﾝのﾈﾊﾞｰﾗﾝﾄﾞｱﾄﾞﾍﾞﾝﾁｬｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "55",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "248",
    OperatingStatus:
      "【エリア入場制限中】スタンバイパスまたはプライオリティ・アクセス・エントランスをご利用の方のみ案内中",
    SunsetFlg: false,
    DPAStatusCD: "2",
    DPAStatus: "販売していません",
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "発行していません",
    FsStatusCD: "3",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:15",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "248",
        OperatingStatus:
          "【エリア入場制限中】スタンバイパスまたはプライオリティ・アクセス・エントランスをご利用の方のみ案内中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "9000",
    FacilityName: "ファンタジースプリングス・エントリーウェイ",
    FacilityKanaName: "ﾌｧﾝﾀｼﾞｰｽﾌﾟﾘﾝｸﾞｽ･ｴﾝﾄﾘｰｳｪｲ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: false,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "6:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "23:00",
    OperatingStatusCD: "201",
    OperatingStatus: "【エリア入場制限中】運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "6:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "23:00",
        SunsetFlg: false,
        OperatingStatusCD: "201",
        OperatingStatus: "【エリア入場制限中】運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "258",
    FacilityName: "フェアリー・ティンカーベルのビジーバギー",
    FacilityKanaName: "ﾌｪｱﾘｰ･ﾃｨﾝｶｰﾍﾞﾙのﾋﾞｼﾞｰﾊﾞｷﾞｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "15",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "226",
    OperatingStatus: "【エリア入場制限中】スタンバイパスがある方のみ案内中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "発行していません",
    FsStatusCD: "3",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:13",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "226",
        OperatingStatus: "【エリア入場制限中】スタンバイパスがある方のみ案内中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "244",
    FacilityName: "フォートレス・エクスプロレーション",
    FacilityKanaName: "ﾌｫｰﾄﾚｽ･ｴｸｽﾌﾟﾛﾚｰｼｮﾝ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: false,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "245",
    FacilityName:
      "フォートレス・エクスプロレーション“ザ・レオナルドチャレンジ”",
    FacilityKanaName: "ﾌｫｰﾄﾚｽ･ｴｸｽﾌﾟﾛﾚｰｼｮﾝ“ｻﾞ･ﾚｵﾅﾙﾄﾞﾁｬﾚﾝｼﾞ”",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: null,
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "12:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "16:00",
    OperatingStatusCD: "002",
    OperatingStatus: "案内終了",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "16:00",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "12:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "16:00",
        SunsetFlg: false,
        OperatingStatusCD: "002",
        OperatingStatus: "案内終了",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "237",
    FacilityName: "フランダーのフライングフィッシュコースター",
    FacilityKanaName: "ﾌﾗﾝﾀﾞｰのﾌﾗｲﾝｸﾞﾌｨｯｼｭｺｰｽﾀｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:06",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "240",
    FacilityName: "ブローフィッシュ・バルーンレース",
    FacilityKanaName: "ﾌﾞﾛｰﾌｨｯｼｭ･ﾊﾞﾙｰﾝﾚｰｽ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "40",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:12",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "226",
    FacilityName: "マジックランプシアター",
    FacilityKanaName: "ﾏｼﾞｯｸﾗﾝﾌﾟｼｱﾀｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "45",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "10:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "20:35",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: "2",
    PPStatus: "40周年記念プライオリティパス発行なし",
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "40周年記念プライオリティパス発行なし",
    FsStatusCD: "5",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:48",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "10:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "20:35",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "221",
    FacilityName: "マーメイドラグーンシアター",
    FacilityKanaName: "ﾏｰﾒｲﾄﾞﾗｸﾞｰﾝｼｱﾀｰ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: "003",
    FacilityStatus: "運営・公演中止",
    StandbyTime: "0",
    OperatingHoursFromDate: null,
    OperatingHoursFrom: null,
    OperatingHoursToDate: null,
    OperatingHoursTo: null,
    OperatingStatusCD: null,
    OperatingStatus: null,
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: false,
    OperatingChgFlg: false,
    UpdateTime: "9:00",
    operatingHours: null,
  },
  {
    FacilityID: "256",
    FacilityName: "ラプンツェルのランタンフェスティバル",
    FacilityKanaName: "ﾗﾌﾟﾝﾂｪﾙのﾗﾝﾀﾝﾌｪｽﾃｨﾊﾞﾙ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "65",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "248",
    OperatingStatus:
      "【エリア入場制限中】スタンバイパスまたはプライオリティ・アクセス・エントランスをご利用の方のみ案内中",
    SunsetFlg: false,
    DPAStatusCD: "2",
    DPAStatus: "販売していません",
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "発行していません",
    FsStatusCD: "3",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:11",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "248",
        OperatingStatus:
          "【エリア入場制限中】スタンバイパスまたはプライオリティ・アクセス・エントランスをご利用の方のみ案内中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "242",
    FacilityName: "レイジングスピリッツ",
    FacilityKanaName: "ﾚｲｼﾞﾝｸﾞｽﾋﾟﾘｯﾂ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "40",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: "2",
    PPStatus: "40周年記念プライオリティパス発行なし",
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "40周年記念プライオリティパス発行なし",
    FsStatusCD: "5",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: true,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:18",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "241",
    FacilityName: "ワールプール",
    FacilityKanaName: "ﾜｰﾙﾌﾟｰﾙ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "30",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:30",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "15:49",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:30",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "230",
    FacilityName: "ヴェネツィアン・ゴンドラ",
    FacilityKanaName: "ｳﾞｪﾈﾂｨｱﾝ･ｺﾞﾝﾄﾞﾗ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "5",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: null,
    PPStatus: null,
    Fsflg: false,
    FsStatusflg: null,
    FsStatus: null,
    FsStatusCD: null,
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "16:01",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
  {
    FacilityID: "224",
    FacilityName: "海底２万マイル",
    FacilityKanaName: "海底2万ﾏｲﾙ",
    NewFlg: false,
    FacilityURLSP: null,
    FacilityStatusCD: null,
    FacilityStatus: null,
    StandbyTime: "40",
    OperatingHoursFromDate: "20241102",
    OperatingHoursFrom: "9:00",
    OperatingHoursToDate: "20241102",
    OperatingHoursTo: "21:00",
    OperatingStatusCD: "001",
    OperatingStatus: "運営中",
    SunsetFlg: false,
    DPAStatusCD: null,
    DPAStatus: null,
    PPStatusCD: "2",
    PPStatus: "40周年記念プライオリティパス発行なし",
    Fsflg: true,
    FsStatusflg: false,
    FsStatus: "40周年記念プライオリティパス発行なし",
    FsStatusCD: "5",
    FsStatusStartDate: null,
    FsStatusStartTime: null,
    FsStatusEndDate: null,
    FsStatusEndTime: null,
    UseLimitFlg: false,
    UseStandbyTimeStyle: true,
    OperatingChgFlg: false,
    UpdateTime: "17:16",
    operatingHours: [
      {
        OperatingHoursFromDate: "20241102",
        OperatingHoursFrom: "9:00",
        OperatingHoursToDate: "20241102",
        OperatingHoursTo: "21:00",
        SunsetFlg: false,
        OperatingStatusCD: "001",
        OperatingStatus: "運営中",
        OperatingChgFlg: false,
      },
    ],
  },
];

export const mockTdsRespHandler = http.get(
  "https://www.tokyodisneyresort.jp/_/realtime/tds_attraction.json",
  () => HttpResponse.json(mockTdsResp),
);

export const mockTdlGreetingResp = {
  id11: {
    AreaJName: "ワールドバザール",
    AreaMName: "ﾜｰﾙﾄﾞﾊﾞｻﾞｰﾙ",
    Facility: [
      {
        greeting: {
          FacilityID: "908",
          FacilityName:
            "メインストリート・ハウス前（キャラクターグリーティング）",
          FacilityKanaName: "ﾒｲﾝｽﾄﾘｰﾄ･ﾊｳｽ前(ｷｬﾗｸﾀｰｸﾞﾘｰﾃｨﾝｸﾞ)",
          NewFlg: false,
          AreaJName: "ワールドバザール",
          AreaMName: "ﾜｰﾙﾄﾞﾊﾞｻﾞｰﾙ",
          FacilityURLSP: null,
          FacilityStatusCD: null,
          FacilityStatus: null,
          StandbyTime: null,
          operatinghours: [
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "9:30",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "12:30",
              OperatingStatusCD: "039",
              OperatingStatus: "案内終了",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
          ],
          UseStandbyTimeStyle: false,
          UpdateTime: "17:30",
        },
      },
    ],
  },
  id13: {
    AreaJName: "ウエスタンランド",
    AreaMName: "ｳｴｽﾀﾝﾗﾝﾄﾞ",
    Facility: [
      {
        greeting: {
          FacilityID: "917",
          FacilityName: "ウッドチャック・グリーティングトレイル（デイジー）",
          FacilityKanaName: "ｳｯﾄﾞﾁｬｯｸ･ｸﾞﾘｰﾃｨﾝｸﾞﾄﾚｲﾙ(ﾃﾞｲｼﾞｰ)",
          NewFlg: false,
          AreaJName: "ウエスタンランド",
          AreaMName: "ｳｴｽﾀﾝﾗﾝﾄﾞ",
          FacilityURLSP: null,
          FacilityStatusCD: null,
          FacilityStatus: null,
          StandbyTime: "25",
          operatinghours: [
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "9:00",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "19:15",
              OperatingStatusCD: "001",
              OperatingStatus: "運営中",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
          ],
          UseStandbyTimeStyle: true,
          UpdateTime: "17:24",
        },
      },
      {
        greeting: {
          FacilityID: "916",
          FacilityName: "ウッドチャック・グリーティングトレイル（ドナルド）",
          FacilityKanaName: "ｳｯﾄﾞﾁｬｯｸ･ｸﾞﾘｰﾃｨﾝｸﾞﾄﾚｲﾙ(ﾄﾞﾅﾙﾄﾞ)",
          NewFlg: false,
          AreaJName: "ウエスタンランド",
          AreaMName: "ｳｴｽﾀﾝﾗﾝﾄﾞ",
          FacilityURLSP: null,
          FacilityStatusCD: null,
          FacilityStatus: null,
          StandbyTime: "40",
          operatinghours: [
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "9:00",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "19:15",
              OperatingStatusCD: "001",
              OperatingStatus: "運営中",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
          ],
          UseStandbyTimeStyle: true,
          UpdateTime: "17:24",
        },
      },
    ],
  },
  id16: {
    AreaJName: "トゥーンタウン",
    AreaMName: "ﾄｩｰﾝﾀｳﾝ",
    Facility: [
      {
        greeting: {
          FacilityID: "909",
          FacilityName: "ミッキーの家とミート・ミッキー",
          FacilityKanaName: "ﾐｯｷｰの家とﾐｰﾄ･ﾐｯｷｰ",
          NewFlg: false,
          AreaJName: "トゥーンタウン",
          AreaMName: "ﾄｩｰﾝﾀｳﾝ",
          FacilityURLSP: null,
          FacilityStatusCD: null,
          FacilityStatus: null,
          StandbyTime: "35",
          operatinghours: [
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "9:00",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "21:00",
              OperatingStatusCD: "001",
              OperatingStatus: "運営中",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
          ],
          UseStandbyTimeStyle: true,
          UpdateTime: "17:26",
        },
      },
      {
        greeting: {
          FacilityID: "890",
          FacilityName: "ミニーのスタイルスタジオ",
          FacilityKanaName: "ﾐﾆｰのｽﾀｲﾙｽﾀｼﾞｵ",
          NewFlg: false,
          AreaJName: "トゥーンタウン",
          AreaMName: "ﾄｩｰﾝﾀｳﾝ",
          FacilityURLSP: null,
          FacilityStatusCD: null,
          FacilityStatus: null,
          StandbyTime: "35",
          operatinghours: [
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "9:00",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "21:00",
              OperatingStatusCD: "001",
              OperatingStatus: "運営中",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
          ],
          UseStandbyTimeStyle: true,
          UpdateTime: "17:19",
        },
      },
    ],
  },
};

export const mockTdlGreetingRespHandler = http.get(
  "https://www.tokyodisneyresort.jp/_/realtime/tdl_greeting.json",
  () => HttpResponse.json(mockTdlGreetingResp),
);

export const mockTdsGreetingResp = {
  id22: {
    AreaJName: "アメリカンウォーターフロント",
    AreaMName: "ｱﾒﾘｶﾝｳｫｰﾀｰﾌﾛﾝﾄ",
    Facility: [
      {
        greeting: {
          FacilityID: "905",
          FacilityName: "ヴィレッジ・グリーティングプレイス",
          FacilityKanaName: "ｳﾞｨﾚｯｼﾞ･ｸﾞﾘｰﾃｨﾝｸﾞﾌﾟﾚｲｽ",
          NewFlg: false,
          AreaJName: "アメリカンウォーターフロント",
          AreaMName: "ｱﾒﾘｶﾝｳｫｰﾀｰﾌﾛﾝﾄ",
          FacilityURLSP: null,
          FacilityStatusCD: null,
          FacilityStatus: null,
          StandbyTime: "60",
          operatinghours: [
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "9:30",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "20:00",
              OperatingStatusCD: "001",
              OperatingStatus: "運営中",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
          ],
          UseStandbyTimeStyle: true,
          UpdateTime: "17:05",
        },
      },
    ],
  },
  id25: {
    AreaJName: "ロストリバーデルタ",
    AreaMName: "ﾛｽﾄﾘﾊﾞｰﾃﾞﾙﾀ",
    Facility: [
      {
        greeting: {
          FacilityID: "904",
          FacilityName: "“サルードス・アミーゴス！”グリーティングドック",
          FacilityKanaName: "“ｻﾙｰﾄﾞｽ･ｱﾐｰｺﾞｽ!”ｸﾞﾘｰﾃｨﾝｸﾞﾄﾞｯｸ",
          NewFlg: false,
          AreaJName: "ロストリバーデルタ",
          AreaMName: "ﾛｽﾄﾘﾊﾞｰﾃﾞﾙﾀ",
          FacilityURLSP: null,
          FacilityStatusCD: null,
          FacilityStatus: null,
          StandbyTime: "70",
          operatinghours: [
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "9:30",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "20:00",
              OperatingStatusCD: "001",
              OperatingStatus: "運営中",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
          ],
          UseStandbyTimeStyle: true,
          UpdateTime: "17:21",
        },
      },
      {
        greeting: {
          FacilityID: "903",
          FacilityName:
            "ミッキー＆フレンズ・グリーティングトレイル（ドナルド）",
          FacilityKanaName: "ﾐｯｷｰ&ﾌﾚﾝｽﾞ･ｸﾞﾘｰﾃｨﾝｸﾞﾄﾚｲﾙ(ﾄﾞﾅﾙﾄﾞ)",
          NewFlg: false,
          AreaJName: "ロストリバーデルタ",
          AreaMName: "ﾛｽﾄﾘﾊﾞｰﾃﾞﾙﾀ",
          FacilityURLSP: null,
          FacilityStatusCD: null,
          FacilityStatus: null,
          StandbyTime: "40",
          operatinghours: [
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "9:30",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "20:00",
              OperatingStatusCD: "001",
              OperatingStatus: "運営中",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
          ],
          UseStandbyTimeStyle: true,
          UpdateTime: "17:12",
        },
      },
      {
        greeting: {
          FacilityID: "901",
          FacilityName:
            "ミッキー＆フレンズ・グリーティングトレイル（ミッキー）",
          FacilityKanaName: "ﾐｯｷｰ&ﾌﾚﾝｽﾞ･ｸﾞﾘｰﾃｨﾝｸﾞﾄﾚｲﾙ(ﾐｯｷｰ)",
          NewFlg: false,
          AreaJName: "ロストリバーデルタ",
          AreaMName: "ﾛｽﾄﾘﾊﾞｰﾃﾞﾙﾀ",
          FacilityURLSP: null,
          FacilityStatusCD: null,
          FacilityStatus: null,
          StandbyTime: "45",
          operatinghours: [
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "9:30",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "20:00",
              OperatingStatusCD: "001",
              OperatingStatus: "運営中",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
          ],
          UseStandbyTimeStyle: true,
          UpdateTime: "17:16",
        },
      },
      {
        greeting: {
          FacilityID: "902",
          FacilityName: "ミッキー＆フレンズ・グリーティングトレイル（ミニー）",
          FacilityKanaName: "ﾐｯｷｰ&ﾌﾚﾝｽﾞ･ｸﾞﾘｰﾃｨﾝｸﾞﾄﾚｲﾙ(ﾐﾆｰ)",
          NewFlg: false,
          AreaJName: "ロストリバーデルタ",
          AreaMName: "ﾛｽﾄﾘﾊﾞｰﾃﾞﾙﾀ",
          FacilityURLSP: null,
          FacilityStatusCD: null,
          FacilityStatus: null,
          StandbyTime: "40",
          operatinghours: [
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "9:30",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "20:00",
              OperatingStatusCD: "001",
              OperatingStatus: "運営中",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
          ],
          UseStandbyTimeStyle: true,
          UpdateTime: "17:16",
        },
      },
    ],
  },
  id28: {
    AreaJName: "パークエントランス",
    AreaMName: "ﾊﾟｰｸｴﾝﾄﾗﾝｽ",
    Facility: [
      {
        greeting: {
          FacilityID: "921",
          FacilityName: "ディズニーシー・プラザ（キャラクターグリーティング）",
          FacilityKanaName: "ﾃﾞｨｽﾞﾆｰｼｰ･ﾌﾟﾗｻﾞ(ｷｬﾗｸﾀｰｸﾞﾘｰﾃｨﾝｸﾞ)",
          NewFlg: false,
          AreaJName: "パークエントランス",
          AreaMName: "ﾊﾟｰｸｴﾝﾄﾗﾝｽ",
          FacilityURLSP: null,
          FacilityStatusCD: null,
          FacilityStatus: null,
          StandbyTime: null,
          operatinghours: [
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "9:15",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "12:15",
              OperatingStatusCD: "002",
              OperatingStatus: "案内終了",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
            {
              OperatingHoursFromDate: "20241102",
              OperatingHoursFrom: "13:35",
              OperatingHoursToDate: "20241102",
              OperatingHoursTo: "15:00",
              OperatingStatusCD: "002",
              OperatingStatus: "案内終了",
              OperatingChgFlg: false,
              SunsetFlg: false,
            },
          ],
          UseStandbyTimeStyle: false,
          UpdateTime: "14:08",
        },
      },
    ],
  },
};

export const mockTdsGreetingRespHandler = http.get(
  "https://www.tokyodisneyresort.jp/_/realtime/tds_greeting.json",
  () => HttpResponse.json(mockTdsGreetingResp),
);
