# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket = "shusann-terraform-state"
    key = "disney-wait-time-app/dev/./terraform.tfstate"
    region = "ap-northeast-1"
    encrypt = true
  }
}
